Fix import error: remove setRequestLocale (not available in next-intl 3.26.5)
- Remove setRequestLocale import that doesn't exist in current version
- Revert to basic next-intl configuration without static export
- Should fix TypeScript compilation error on Vercel